name: Build snake

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, macos-10.14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install dependencies on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install xorg-dev
      
      - name: Set arch and os variables on linux and macos
        id: info
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        run:
          echo "arch=$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)" >> $GITHUB_STATE
          echo "os=$(uname -s | tr '[:upper:]' '[:lower:]')" >> $GITHUB_STATE
        
      - name: Build with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -B build
          cmake --build build --config Release

      - name: Export artifacts on ubuntu and macos
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v4
        with:
          name: snake-${{ steps.info.outputs.os }}-${{ steps.info.outputs.arch }}
          path: build/snake

      - name: Export artifacts on windows
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: snake-windows-amd64
          path: build/Release/snake.exe
